### ISSUE TITLE
Regenerate wrapper for newest zmq version.

### ISSUE THREAD

**Issue by dom96** [nim-lang/nim-zmq#1]
This wrapper only supports version 2.x.x. The newest version is 4.x.x. Issues occur as a result of this (https://github.com/Araq/Nimrod/issues/1421)

**Comment by nevercast** [comment]
Was this closed by https://github.com/nim-lang/nim-zmq/commit/68872f29083a084a2642a097cdbce6ba72aa0e1c ?
